Feature/php pre challenge2
ryoma-yama/quelcode-php pull request #2
Opened 2020-05-20 08:39 UTC by ryoma-yama

22-練習課題２を提出します。提出前のセルフチェックとして, 期待する動作と同じ出力結果になることを確認しています。

2020-05-20 09:57 UTC, yusaku-inamura requested changes
確認してコメントしました!
もう一点重要なこととして、ソート時に余計なループが発生してしまっています。
もう少しこのソート方法について深掘りしてみて、最低何回のループでソートを完成させることができるかを意識してコードを書いてみてください 🙌

2020-05-20 09:57 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +  for ($j = 1; $j < count($array); $j++) {
`count()` をfor文の条件として使用していますが、この書き方だとループのたびに関数が呼び出されてしまうので、別の変数に入れておいて、その変数を条件として使用するのが良いですね。

2020-05-20 09:57 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
>  for ($i = 0; $i < count($array); $i++) {
インデントが半角スペース二つになっていますが、特に指定がない場合は基本的に半角スペース4つにしておくことを勧めておきます。
理由としてはメジャーなコーディング規約(PSR-2)にてそう決められているからですね。
プロジェクトのコーディングルールがある場合はそちらに従ってしまってOKです。

2020-05-20 09:57 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +    if ($array[$i] > $array[$i + $j] && $array[$i + $j] !== null) {
`$array[$i + $j] !== null` でキーの存在を確認しているのはすごくいい! ・・・・のですが、そもそもこのソート方法を使用するのであればキーを確認する必要はないはずなのです 😢 
このソート方法、おそらく調べてたどり着いたものだと思いますので、もう少し掘り下げてみて欲しいです 💪

2020-05-20 09:57 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +    if ($array[$i] > $array[$i + $j] && $array[$i + $j] !== null) {
繰り返しですが、存在しない可能性のある配列のキーにアクセスする場合に存在チェックを行う、という観点自体はとてもぐっどなのでその意識は持ち続けてほしいですね~ 👍

2020-05-22 03:45 UTC, choimake commented
対応ありがとうございました。LGTMです。
特に修正の必要はありませんが、このソートは実は結構サッパリ書けるので載せておきます。
参考にしてみてください。

```
$length = count($array);
for ($i = 0; $i < $length - 1; $i++) {
    for ($j = $i + 1; $j < $length; $j++) {
        if ($array[$i] > $array[$j]) {
            $tmp = $array[$j];
            $array[$j] = $array[$i];
            $array[$i] = $tmp;
        }
    }
}
```

2020-06-09 06:25 UTC, merged